# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrxoceV-HtccJjKTyVK44cwjRyBPlthZ
"""

import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# SMART PARKING OPTIMIZATION USING PARTICLE SWARM OPTIMIZATION
# Based on the objective formulation of Sahu et al.
#
# Objective:
# Minimize:
# F = w1*Ts + w2*Es + w3*C + w4*(1-U)
#
# where:
# Ts = parking search time
# Es = energy consumption
# C  = traffic congestion
# U  = parking-space utilization
# ============================================================


# ============================================================
# 1. PROBLEM SETUP
# ============================================================

np.random.seed(42)

# Number of vehicles requesting parking
NUM_VEHICLES = 10

# Number of parking lots
NUM_PARKING_LOTS = 5

# Parking capacity of each lot
parking_capacity = np.array([3, 2, 3, 2, 3])

# Current occupied spaces before new requests
initial_occupancy = np.array([1, 1, 1, 0, 1])

# ------------------------------------------------------------
# Distance matrix
#
# distance[v][p]
# = distance of vehicle v from parking lot p
# ------------------------------------------------------------

distance = np.array([
    [2.0, 6.0, 4.0, 8.0, 5.0],
    [7.0, 3.0, 6.0, 5.0, 8.0],
    [5.0, 8.0, 2.0, 6.0, 4.0],
    [3.0, 7.0, 5.0, 2.0, 6.0],
    [8.0, 4.0, 7.0, 3.0, 5.0],
    [4.0, 6.0, 3.0, 7.0, 2.0],
    [6.0, 2.0, 8.0, 4.0, 7.0],
    [3.0, 5.0, 4.0, 6.0, 2.0],
    [7.0, 3.0, 5.0, 2.0, 6.0],
    [4.0, 8.0, 2.0, 7.0, 3.0]
])


# ============================================================
# 2. VEHICLE SPEED
# ============================================================

# Speed of each vehicle in km/h
speed = np.array([
    30, 25, 35, 28, 32,
    30, 27, 35, 31, 29
])


# ============================================================
# 3. ENERGY MODEL
# ============================================================

# Energy consumed per kilometer
# Simplified simulation value.
ENERGY_PER_KM = 1.5


# ============================================================
# 4. CONGESTION LEVEL OF EACH PARKING LOT
# ============================================================

# Higher value = more congestion around that parking lot
base_congestion = np.array([
    0.30,
    0.60,
    0.25,
    0.70,
    0.40
])


# ============================================================
# 5. PSO PARAMETERS
# ============================================================

NUM_PARTICLES = 30
MAX_ITERATIONS = 100

# Standard PSO parameters
w = 0.7
c1 = 1.5
c2 = 1.5

# ------------------------------------------------------------
# Objective weights
#
# w1 -> search time
# w2 -> energy
# w3 -> congestion
# w4 -> unused parking spaces
# ------------------------------------------------------------

weight_time = 0.35
weight_energy = 0.25
weight_congestion = 0.25
weight_utilization = 0.15


# ============================================================
# 6. HELPER FUNCTION
# ============================================================

def repair_solution(solution):
    """
    Makes sure that a particle represents a feasible
    parking allocation.

    Each vehicle must be assigned to one parking lot.

    Parking capacity must not be exceeded.
    """

    solution = np.rint(solution).astype(int)

    # Keep parking lot values inside valid range
    solution = np.clip(
        solution,
        0,
        NUM_PARKING_LOTS - 1
    )

    # Count vehicles assigned to each parking lot
    counts = np.bincount(
        solution,
        minlength=NUM_PARKING_LOTS
    )

    # Available capacity for new vehicles
    available_capacity = (
        parking_capacity - initial_occupancy
    )

    # Find overloaded parking lots
    for lot in range(NUM_PARKING_LOTS):

        while counts[lot] > available_capacity[lot]:

            # Find vehicles currently assigned to this lot
            vehicles = np.where(solution == lot)[0]

            # Randomly choose one vehicle
            vehicle = np.random.choice(vehicles)

            # Find feasible alternative lots
            alternatives = []

            for new_lot in range(NUM_PARKING_LOTS):

                if counts[new_lot] < available_capacity[new_lot]:
                    alternatives.append(new_lot)

            # If no alternative exists, keep the assignment
            if len(alternatives) == 0:
                break

            # Select the alternative with smallest distance
            best_lot = min(
                alternatives,
                key=lambda x: distance[vehicle][x]
            )

            solution[vehicle] = best_lot

            counts[lot] -= 1
            counts[best_lot] += 1

    return solution


# ============================================================
# 7. CALCULATE OBJECTIVE COMPONENTS
# ============================================================

def calculate_metrics(solution):

    solution = repair_solution(solution)

    total_time = 0
    total_energy = 0

    # Number of vehicles assigned to each parking lot
    assigned_count = np.bincount(
        solution,
        minlength=NUM_PARKING_LOTS
    )

    # --------------------------------------------------------
    # Calculate search time and energy
    # --------------------------------------------------------

    for vehicle in range(NUM_VEHICLES):

        lot = solution[vehicle]

        # Distance
        d = distance[vehicle][lot]

        # Speed
        v = speed[vehicle]

        # Time = distance / speed
        # Convert hours to minutes
        travel_time = (d / v) * 60

        total_time += travel_time

        # Energy proportional to distance
        energy = d * ENERGY_PER_KM

        total_energy += energy

    # Average search/travel time
    average_time = total_time / NUM_VEHICLES

    # Average energy
    average_energy = total_energy / NUM_VEHICLES

    # --------------------------------------------------------
    # Congestion
    # --------------------------------------------------------

    congestion_values = []

    for lot in range(NUM_PARKING_LOTS):

        # Occupancy after allocation
        occupied = (
            initial_occupancy[lot]
            + assigned_count[lot]
        )

        capacity = parking_capacity[lot]

        utilization = occupied / capacity

        # Congestion increases with utilization
        congestion = (
            base_congestion[lot]
            + 0.5 * utilization
        )

        congestion_values.append(congestion)

    average_congestion = np.mean(congestion_values)

    # --------------------------------------------------------
    # Parking utilization
    # --------------------------------------------------------

    total_capacity = np.sum(parking_capacity)

    total_occupied = (
        np.sum(initial_occupancy)
        + NUM_VEHICLES
    )

    utilization = total_occupied / total_capacity

    return (
        average_time,
        average_energy,
        average_congestion,
        utilization
    )


# ============================================================
# 8. NORMALIZATION
# ============================================================

def normalize(value, minimum, maximum):

    if maximum == minimum:
        return 0

    return (value - minimum) / (maximum - minimum)


# ============================================================
# 9. FITNESS FUNCTION
# ============================================================

def fitness(solution):

    time, energy, congestion, utilization = \
        calculate_metrics(solution)

    # --------------------------------------------------------
    # Normalize objective values
    # --------------------------------------------------------

    # Expected approximate ranges
    normalized_time = normalize(
        time,
        0,
        20
    )

    normalized_energy = normalize(
        energy,
        0,
        15
    )

    normalized_congestion = normalize(
        congestion,
        0,
        1.5
    )

    # We want HIGH utilization.
    # Therefore minimize (1 - utilization)
    unused_space = 1 - utilization

    # --------------------------------------------------------
    # Sahu et al. objective:
    #
    # F = w1 Ts + w2 Es + w3 C + w4(1-U)
    # --------------------------------------------------------

    F = (
        weight_time * normalized_time
        +
        weight_energy * normalized_energy
        +
        weight_congestion * normalized_congestion
        +
        weight_utilization * unused_space
    )

    return F


# ============================================================
# 10. INITIALIZE PARTICLES
# ============================================================

positions = np.random.uniform(
    0,
    NUM_PARKING_LOTS - 1,
    size=(
        NUM_PARTICLES,
        NUM_VEHICLES
    )
)

velocities = np.random.uniform(
    -1,
    1,
    size=(
        NUM_PARTICLES,
        NUM_VEHICLES
    )
)


# Repair initial particles
for i in range(NUM_PARTICLES):

    positions[i] = repair_solution(
        positions[i]
    )


# ============================================================
# 11. PERSONAL BEST
# ============================================================

pbest_positions = positions.copy()

pbest_values = np.array([
    fitness(position)
    for position in pbest_positions
])


# ============================================================
# 12. GLOBAL BEST
# ============================================================

best_index = np.argmin(pbest_values)

gbest_position = pbest_positions[
    best_index
].copy()

gbest_value = pbest_values[
    best_index
]


# ============================================================
# 13. STORE FITNESS HISTORY
# ============================================================

fitness_history = []


# ============================================================
# 14. PSO MAIN LOOP
# ============================================================

for iteration in range(MAX_ITERATIONS):

    for particle in range(NUM_PARTICLES):

        # ----------------------------------------------------
        # Generate random values
        # ----------------------------------------------------

        r1 = np.random.rand(NUM_VEHICLES)
        r2 = np.random.rand(NUM_VEHICLES)

        # ----------------------------------------------------
        # Velocity update
        #
        # v = w*v
        #     + c1*r1*(pbest-x)
        #     + c2*r2*(gbest-x)
        # ----------------------------------------------------

        velocities[particle] = (
            w * velocities[particle]
            +
            c1 * r1 *
            (
                pbest_positions[particle]
                -
                positions[particle]
            )
            +
            c2 * r2 *
            (
                gbest_position
                -
                positions[particle]
            )
        )

        # ----------------------------------------------------
        # Position update
        #
        # x = x + v
        # ----------------------------------------------------

        positions[particle] = (
            positions[particle]
            +
            velocities[particle]
        )

        # ----------------------------------------------------
        # Repair parking assignment
        # ----------------------------------------------------

        positions[particle] = repair_solution(
            positions[particle]
        )

        # ----------------------------------------------------
        # Evaluate fitness
        # ----------------------------------------------------

        current_fitness = fitness(
            positions[particle]
        )

        # ----------------------------------------------------
        # Update personal best
        # ----------------------------------------------------

        if current_fitness < pbest_values[particle]:

            pbest_values[particle] = current_fitness

            pbest_positions[particle] = \
                positions[particle].copy()

        # ----------------------------------------------------
        # Update global best
        # ----------------------------------------------------

        if current_fitness < gbest_value:

            gbest_value = current_fitness

            gbest_position = \
                positions[particle].copy()

    # Store best fitness
    fitness_history.append(gbest_value)

    print(
        f"Iteration {iteration + 1:3d} "
        f"| Best Fitness = {gbest_value:.6f}"
    )


# ============================================================
# 15. FINAL SOLUTION
# ============================================================

best_solution = repair_solution(
    gbest_position
)


# ============================================================
# 16. FINAL METRICS
# ============================================================

final_time, final_energy, \
final_congestion, final_utilization = \
    calculate_metrics(best_solution)


# ============================================================
# 17. DISPLAY FINAL RESULT
# ============================================================

print("\n")
print("=" * 60)
print("             FINAL PSO PARKING SOLUTION")
print("=" * 60)

print("\nVehicle → Parking Lot")

for vehicle in range(NUM_VEHICLES):

    print(
        f"Vehicle {vehicle + 1:2d}"
        f" → Parking Lot {best_solution[vehicle] + 1}"
    )

print("\nBest Fitness :", round(gbest_value, 6))

print(
    "Average Search Time :",
    round(final_time, 3),
    "minutes"
)

print(
    "Average Energy      :",
    round(final_energy, 3),
    "units"
)

print(
    "Congestion Level    :",
    round(final_congestion, 3)
)

print(
    "Parking Utilization :",
    round(final_utilization * 100, 2),
    "%"
)


# ============================================================
# 18. PARKING LOT OCCUPANCY
# ============================================================

final_counts = np.bincount(
    best_solution,
    minlength=NUM_PARKING_LOTS
)

print("\nParking Lot Occupancy")

for lot in range(NUM_PARKING_LOTS):

    occupied = (
        initial_occupancy[lot]
        +
        final_counts[lot]
    )

    print(
        f"Parking Lot {lot + 1}: "
        f"{occupied}/{parking_capacity[lot]}"
    )


# ============================================================
# 19. GRAPH 1
# FITNESS VS ITERATION
# ============================================================

plt.figure(figsize=(9, 5))

plt.plot(
    range(1, MAX_ITERATIONS + 1),
    fitness_history,
    linewidth=2
)

plt.xlabel("Iteration")
plt.ylabel("Best Fitness")
plt.title(
    "PSO Convergence - Smart Parking Optimization"
)

plt.grid(True)

plt.show()


# ============================================================
# 20. GRAPH 2
# PARKING ALLOCATION
# ============================================================

plt.figure(figsize=(9, 5))

vehicles = np.arange(
    1,
    NUM_VEHICLES + 1
)

parking_numbers = best_solution + 1

plt.scatter(
    vehicles,
    parking_numbers,
    s=100
)

plt.xlabel("Vehicle Number")
plt.ylabel("Assigned Parking Lot")

plt.title(
    "Optimized Vehicle-to-Parking Allocation"
)

plt.yticks(
    range(1, NUM_PARKING_LOTS + 1)
)

plt.grid(True)

plt.show()


# ============================================================
# 21. GRAPH 3
# PARKING UTILIZATION
# ============================================================

plt.figure(figsize=(9, 5))

lot_numbers = np.arange(
    1,
    NUM_PARKING_LOTS + 1
)

utilization_values = []

for lot in range(NUM_PARKING_LOTS):

    occupied = (
        initial_occupancy[lot]
        +
        final_counts[lot]
    )

    utilization_values.append(
        occupied / parking_capacity[lot]
    )

plt.bar(
    lot_numbers,
    utilization_values
)

plt.xlabel("Parking Lot")
plt.ylabel("Utilization")

plt.title(
    "Parking Lot Utilization After PSO"
)

plt.xticks(
    lot_numbers
)

plt.ylim(
    0,
    1.1
)

plt.grid(
    axis="y"
)

plt.show()